# -*- coding: utf-8 -*-
"""barcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAbrtVXFnmoYQoLG6DDxCaaVHiJtGp8o
"""

import barcode
from barcode.writer import ImageWriter

data = '123456789'
code128 = barcode.get_barcode_class('code128')
code128_instance = code128(data, writer=ImageWriter())

filename = 'barcode'
code128_instance.save(filename)